import io

from .pipeline import Pipeline, PipelineConfig


def test_pipeline_simple_debug():
    cfg = PipelineConfig.model_validate(
        {
            "pipe": [
                {"engine": "in:memory"},
                {"engine": "extract:raw"},
                {"engine": "redact:noop", "delimiters": ["[", "]"]},
                {"engine": "render:text"},
                {"engine": "out:memory"},
            ],
        }
    )
    # Run the pipeline.
    pipe = Pipeline(cfg)

    in_buf = io.BytesIO(b"Hello, world!")
    out_buf = io.BytesIO()

    ctx = pipe.run(
        {
            "debug": True,
            "in": {
                "buffer": in_buf,
            },
            "out": {
                "buffer": out_buf,
            },
        }
    )

    assert out_buf.getvalue() == (
        b"Blind Charging - Redacted Narrative\n\n\nThe following narrative has been a"
        b"utomatically extracted from its original police report.\nThe narrative ha"
        b"s been redacted to remove race-specific information, but has otherwise not b"
        b"een modified.\n\nThis document was generated by an experimental version of"
        b" the Blind Charging tool. Please report any issues to\n        blind-char"
        b"ging@lists.stanford.edu.\n\n\n=== NARRATIVE ===\nHello, world!\n\n=== END "
        b"OF DOCUMENT ===\n"
    )
    assert ctx.debug is True
