from typing import Callable, NamedTuple
from difflib import SequenceMatcher


Styler = Callable[[str, str], str]

Grafer = Callable[[str], str]

Escaper = Callable[[str], str]

Render = Callable[[str, str, str | None], str]


class Renderer(NamedTuple):
    """A renderer for a specific format."""
    name: str
    extension: str
    render: Render


TITLE = "Blind Charging - Redacted Narrative"


DISCLAIMER = """
The following narrative has been automatically extracted from its original police report.
The narrative has been redacted to remove race-specific information, but has otherwise not been modified.
<br/><br/>
This document was generated by an experimental version of the Blind Charging tool. Please report any issues to
<a href="mailto:blind-charging@lists.stanford.edu">blind-charging@lists.stanford.edu</a>.
"""


def escape_for_xml(text: str) -> str:
    """Escape text for HTML-style markup languages (HTML, platypus, etc).

    Args:
        text: The text to escape.

    Returns:
        The escaped text.
    """
    replacements = [
            ('&', '&amp;'),
            ('<', '&lt;'),
            ('>', '&gt;'),
            ]
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def format_narrative(style: Styler,
                     p: Grafer,
                     escape: Escaper,
                     narrative: str,
                     original: str | None = None) -> str:
    """Format a narrative for display as an HTML-style document.

    Args:
        style: The style function to use.
        p: The paragraph formatting function to use.
        escape: The escape function to use.
        narrative: The narrative to format.
        original: The original narrative, if available.

    Returns:
        The formatted narrative.
    """
    final = narrative

    # Compute diff between original and redacted narrative
    if original:
        final = ""
        edit_stack = 0
        matcher = SequenceMatcher(None,
                                  original,
                                  narrative,
                                  autojunk=False)
        diff = matcher.get_opcodes()

        for opcode, i1, i2, j1, j2 in diff:
            if opcode == 'delete':
                continue

            string = narrative[j1:j2]
            stripped = string.strip()
            if stripped and stripped[0] == '<':
                edit_stack += 1

            escaped = escape(string)
            
            if opcode == 'equal':
                if edit_stack > 0:
                    final += style(escaped, 'Redaction')
                else:
                    final += escaped
            elif opcode in {'replace', 'insert'}:
                if edit_stack > 0:
                    final += style(escaped, 'Redaction')
                else:
                    final += style(escaped, 'RedactError')

            if stripped and stripped[-1] == '>':
                edit_stack = max(0, edit_stack - 1)

    final = "".join(p(line) for line in final.splitlines())

    return final
