from functools import cached_property, partial
from typing import Literal

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, StyleSheet1
from reportlab.lib.units import inch
from reportlab.platypus import Frame, PageTemplate, Paragraph, SimpleDocTemplate

from ..common.context import Context
from ..common.file import MemoryFile
from ..common.text import RedactedText, escape_for_xml
from .base import BaseRenderConfig, BaseRenderer


class PdfRenderConfig(BaseRenderConfig):
    """PDF Render config."""

    engine: Literal["render:pdf"]

    @cached_property
    def driver(self) -> "PDFRenderer":
        return PDFRenderer(self)


class PDFRenderer(BaseRenderer):
    def __init__(self, config: PdfRenderConfig) -> None:
        self.config = config

    def __call__(self, redaction: RedactedText, context: Context) -> MemoryFile:
        """Render a narrative to PDF.

        Args:
            redaction: The redaction to render.
        """
        f = MemoryFile()
        styles = self.get_pdf_styles()
        style = partial(self.apply_platypus_style, styles)

        doc = SimpleDocTemplate(
            f.buffer,
            pagesize=letter,
            rightMargin=inch / 2,
            leftMargin=inch / 2,
            topMargin=inch,
            bottomMargin=inch / 2,
        )
        frame = Frame(
            doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id="normal"
        )

        tpl = PageTemplate(
            id="report", frames=[frame], onPage=partial(self.layout_pdf, styles=styles)
        )
        doc.addPageTemplates([tpl])

        formatted = redaction.format(
            style=style,
            p=self.format_platypus_paragraph,
            escape=partial(escape_for_xml, debug=context.debug),
        )
        # Split the paragraphs generated by the formatter.
        # TODO there's probably a better way to do this? maybe just generate an
        # entire document as RML and render that, instead of using this weird
        # SimpleDocTemplate builder?
        paras = [p + "</para>" for p in formatted.split("</para>") if p]

        doc.build(
            [Paragraph(p, styles["Normal"]) for p in paras]
            + [Paragraph(self.DISCLAIMER, styles["Disclaimer"])],
            onFirstPage=partial(self.layout_pdf, styles=styles),
            onLaterPages=partial(self.layout_pdf, styles=styles),
        )

        return f

    def layout_pdf(
        self, canvas, doc, *, styles, line_margin=5, line_thickness=0.5
    ) -> None:
        """Layout the PDF page.

        Args:
            canvas: The canvas to layout.
            doc: The document to layout.
        """
        canvas.saveState()

        # Lines to separate header/footer from content
        line_x0 = doc.leftMargin
        line_x1 = doc.width + doc.leftMargin
        canvas.setLineWidth(line_thickness)

        # Draw the header.
        header_text = Paragraph(self.TITLE, styles["Header"])
        w, h = header_text.wrap(doc.width, doc.topMargin)
        header_text_y = doc.height + (doc.topMargin / 2) + doc.bottomMargin - h
        header_text_x = doc.leftMargin
        header_text.drawOn(canvas, header_text_x, header_text_y)

        # Draw a line under the header
        header_line_y = header_text_y - line_margin
        canvas.line(line_x0, header_line_y, line_x1, header_line_y)

        # Draw the footer
        footer_text = Paragraph(f"Page {doc.page}", styles["Footer"])
        w, h = footer_text.wrap(doc.width, doc.bottomMargin)
        footer_text_y = h
        footer_text_x = doc.leftMargin
        footer_text.drawOn(canvas, footer_text_x, footer_text_y)

        # Draw a line above the footer
        footer_line_y = footer_text_y + line_margin + footer_text_y
        canvas.line(line_x0, footer_line_y, line_x1, footer_line_y)

        canvas.restoreState()

    def get_pdf_styles(self) -> StyleSheet1:
        """Get nice-looking report styles for the PDF."""
        styles = StyleSheet1()
        styles.add(
            ParagraphStyle(
                name="Header",
                fontName="Times-Bold",
                fontSize=10,
                leading=14,
            )
        )
        styles.add(
            ParagraphStyle(
                name="Normal",
                fontName="Times-Roman",
                fontSize=12,
                leading=14,
                spaceAfter=10,
            )
        )
        styles.add(
            ParagraphStyle(
                name="Disclaimer",
                parent=styles["Normal"],
                fontName="Times-Italic",
                fontSize=10,
                # ACW note: I think since this applies to an entire paragraph,
                # `textColor` is the way to set the color for the disclaimer.
                # For the `Redaction` and `RedactError` styles below, they
                # appear as text within paragraphs, so we should use the
                # `color` attribute for those styles.
                textColor="dimgrey",
            )
        )
        styles.add(
            ParagraphStyle(
                name="Footer",
                parent=styles["Normal"],
                fontSize=10,
            )
        )
        styles.add(
            ParagraphStyle(
                name="Redaction",
                parent=styles["Normal"],
                fontName="Courier",
                fontSize=12,
                color="tomato",
            )
        )
        styles.add(
            ParagraphStyle(
                name="RedactError",
                parent=styles["Redaction"],
                color="lightgrey",
            )
        )
        return styles

    def apply_platypus_style(self, styles: StyleSheet1, text: str, style: str) -> str:
        """Style span of text for display.

        Args:
            styles: The styles to use.
            redacted: The text to color.
            style: The name of the style to use.

        Returns:
            The styled text.
        """
        s = styles[style]
        color = s.color
        face = s.fontName

        # Format each line separately, so that when we apply paragraph breaks they
        # don't interfere with the font tags.
        return "\n".join(
            f"<font color='{color}' face='{face}'>{t}</font>" for t in text.splitlines()
        )

    def format_platypus_paragraph(self, text: str) -> str:
        """Format a paragraph for display.

        Args:
            text: The text to format.

        Returns:
            The formatted text.
        """
        return f"<para>{text}</para>"
