from functools import partial

from reportlab.platypus import Frame, PageTemplate, Paragraph, SimpleDocTemplate
from reportlab.lib.styles import ParagraphStyle, StyleSheet1
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch


DISCLAIMER = """
The following narrative has been automatically extracted from its original police report.
The narrative has been redacted to remove race-specific information, but has otherwise not been modified.
<br/><br/>
This document was generated by an experimental version of the Blind Charging tool. Please report any issues to
<a href="mailto:blind-charging@lists.stanford.edu">blind-charging@lists.stanford.edu</a>.
"""


def _escape_for_platypus(text: str) -> str:
    """Escape text for platypus.

    Args:
        text: The text to escape.

    Returns:
        The escaped text.
    """
    return text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('\n', '<br/><br/>')


def layout(canvas, doc, *, styles, line_margin=5, line_thickness=0.5) -> None:
    """Layout the PDF page.

    Args:
        canvas: The canvas to layout.
        doc: The document to layout.
    """
    print(canvas, '\n', canvas.__dict__)
    canvas.saveState()

    # Lines to separate header/footer from content
    line_x0 = doc.leftMargin
    line_x1 = doc.width + doc.leftMargin
    canvas.setLineWidth(line_thickness)

    # Draw the header.
    header_text = Paragraph("Blind Charging - Redacted Narrative", styles["Header"])
    w, h = header_text.wrap(doc.width, doc.topMargin)
    header_text_y = doc.height + (doc.topMargin / 2) + doc.bottomMargin - h
    header_text_x = doc.leftMargin
    header_text.drawOn(canvas, header_text_x, header_text_y)

    # Draw a line under the header
    header_line_y = header_text_y - line_margin
    canvas.line(line_x0, header_line_y, line_x1, header_line_y)

    # Draw the footer
    footer_text = Paragraph(f"Page {doc.page}",
                            styles["Footer"])
    w, h = footer_text.wrap(doc.width, doc.bottomMargin)
    footer_text_y = h
    footer_text_x = doc.leftMargin
    footer_text.drawOn(canvas, footer_text_x, footer_text_y)

    # Draw a line above the footer
    footer_line_y = footer_text_y + line_margin + footer_text_y
    canvas.line(line_x0, footer_line_y, line_x1, footer_line_y)

    canvas.restoreState()


def get_styles():
    """Get nice-looking report styles for the PDF."""
    styles = StyleSheet1()
    styles.add(ParagraphStyle(name='Header',
                              fontName='Times-Bold',
                              fontSize=10,
                              leading=14))
    styles.add(ParagraphStyle(name='Normal',
                              fontName='Times-Roman', fontSize=12,
                              leading=14, spaceAfter=10))
    styles.add(ParagraphStyle(name='Italic', parent=styles['Normal'],
                              fontName='Times-Italic', fontSize=10))
    styles.add(ParagraphStyle(name='Footer', parent=styles['Normal'],
                              fontSize=10))
    return styles


def pdf(out: str, narrative: str) -> None:
    """Render a narrative to PDF.

    Args:
        out: The path to the output file.
        narrative: The narrative to render
    """
    styles = get_styles()

    doc = SimpleDocTemplate(out, pagesize=letter,
                            rightMargin=inch / 2,
                            leftMargin=inch / 2,
                            topMargin=inch / 2,
                            bottomMargin=inch / 2)
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height,
                  id='normal')

    tpl = PageTemplate(id='report', frames=[frame], onPage=partial(layout, styles=styles))
    doc.addPageTemplates([tpl])

    doc.build([
            Paragraph(DISCLAIMER, styles['Italic']),
            Paragraph(_escape_for_platypus(narrative), styles['Normal']),
            ],
            onFirstPage=partial(layout, styles=styles),
            onLaterPages=partial(layout, styles=styles))
