from difflib import SequenceMatcher
from functools import partial
import re

from reportlab.platypus import (
        Frame,
        PageTemplate,
        Paragraph,
        SimpleDocTemplate,
        )
from reportlab.lib.styles import ParagraphStyle, StyleSheet1
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch


DISCLAIMER = """
The following narrative has been automatically extracted from its original police report.
The narrative has been redacted to remove race-specific information, but has otherwise not been modified.
<br/><br/>
This document was generated by an experimental version of the Blind Charging tool. Please report any issues to
<a href="mailto:blind-charging@lists.stanford.edu">blind-charging@lists.stanford.edu</a>.
"""


def _escape_for_platypus(text: str) -> str:
    """Escape text for platypus.

    Args:
        text: The text to escape.

    Returns:
        The escaped text.
    """
    replacements = [
            ('&', '&amp;'),
            ('<', '&lt;'),
            ('>', '&gt;'),
            ('\n', '<br/><br/>'),
            ]
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def layout(canvas, doc, *, styles, line_margin=5, line_thickness=0.5) -> None:
    """Layout the PDF page.

    Args:
        canvas: The canvas to layout.
        doc: The document to layout.
    """
    canvas.saveState()

    # Lines to separate header/footer from content
    line_x0 = doc.leftMargin
    line_x1 = doc.width + doc.leftMargin
    canvas.setLineWidth(line_thickness)

    # Draw the header.
    header_text = Paragraph(
            "Blind Charging - Redacted Narrative",
            styles["Header"])
    w, h = header_text.wrap(doc.width, doc.topMargin)
    header_text_y = doc.height + (doc.topMargin / 2) + doc.bottomMargin - h
    header_text_x = doc.leftMargin
    header_text.drawOn(canvas, header_text_x, header_text_y)

    # Draw a line under the header
    header_line_y = header_text_y - line_margin
    canvas.line(line_x0, header_line_y, line_x1, header_line_y)

    # Draw the footer
    footer_text = Paragraph(f"Page {doc.page}",
                            styles["Footer"])
    w, h = footer_text.wrap(doc.width, doc.bottomMargin)
    footer_text_y = h
    footer_text_x = doc.leftMargin
    footer_text.drawOn(canvas, footer_text_x, footer_text_y)

    # Draw a line above the footer
    footer_line_y = footer_text_y + line_margin + footer_text_y
    canvas.line(line_x0, footer_line_y, line_x1, footer_line_y)

    canvas.restoreState()


def get_styles() -> StyleSheet1:
    """Get nice-looking report styles for the PDF."""
    styles = StyleSheet1()
    styles.add(ParagraphStyle(name='Header',
                              fontName='Times-Bold',
                              fontSize=10,
                              leading=14))
    styles.add(ParagraphStyle(name='Normal',
                              fontName='Times-Roman', fontSize=12,
                              leading=14, spaceAfter=10))
    styles.add(ParagraphStyle(name='Italic', parent=styles['Normal'],
                              fontName='Times-Italic', fontSize=10))
    styles.add(ParagraphStyle(name='Footer', parent=styles['Normal'],
                              fontSize=10))
    styles.add(ParagraphStyle(name='Redaction', parent=styles['Normal'],
                              fontName='Courier', fontSize=12,
                              color="orange"))
    styles.add(ParagraphStyle(name='RedactError', parent=styles['Redaction'],
                              fontName='Courier-Bold',
                              color='red'))
    return styles


def styled(styles: StyleSheet1, text: str, style: str) -> str:
    """Style span of text for display.

    Args:
        text: The text to color.
        style: The name of the style to use.

    Returns:
        The styled text.
    """
    s = styles[style]
    color = s.color
    face = s.fontName
    return f"<font color='{color}' face='{face}'>{text}</font>"


def format_narrative(styles: StyleSheet1,
                     narrative: str,
                     original: str | None = None) -> str:
    """Format a narrative for display.

    Args:
        narrative: The narrative to format.
        original: The original narrative, if available.

    Returns:
        The formatted narrative.
    """
    final = narrative
    style = partial(styled, styles)

    # Compute diff between original and redacted narrative
    if original:
        final = ""
        edit_stack = 0
        matcher = SequenceMatcher(None,
                                  original,
                                  narrative,
                                  autojunk=False)
        diff = matcher.get_opcodes()

        for opcode, i1, i2, j1, j2 in diff:
            if opcode == 'delete':
                continue

            string = narrative[j1:j2]
            stripped = string.strip()
            if stripped and stripped[0] == '<':
                edit_stack += 1

            escaped = _escape_for_platypus(string)
            
            if opcode == 'equal':
                if edit_stack > 0:
                    final += style(escaped, 'Redaction')
                else:
                    final += escaped
            elif opcode in {'replace', 'insert'}:
                if edit_stack > 0:
                    final += style(escaped, 'Redaction')
                else:
                    final += style(escaped, 'RedactError')

            if stripped and stripped[-1] == '>':
                edit_stack = max(0, edit_stack - 1)

    return final


def pdf(out: str, narrative: str, original: str | None = None) -> None:
    """Render a narrative to PDF.

    Args:
        out: The path to the output file.
        narrative: The narrative to render
        original: The original narrative, if available.
    """
    styles = get_styles()

    doc = SimpleDocTemplate(out, pagesize=letter,
                            rightMargin=inch / 2,
                            leftMargin=inch / 2,
                            topMargin=inch / 2,
                            bottomMargin=inch / 2)
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height,
                  id='normal')

    tpl = PageTemplate(
            id='report',
            frames=[frame],
            onPage=partial(layout, styles=styles))
    doc.addPageTemplates([tpl])

    doc.build([
            Paragraph(DISCLAIMER, styles['Italic']),
            Paragraph(format_narrative(styles, narrative, original), styles['Normal']),
            ],
            onFirstPage=partial(layout, styles=styles),
            onLaterPages=partial(layout, styles=styles))
