from abc import ABC, abstractmethod

from ..common.file import MemoryFile
from ..common.text import RedactedText


class BaseRenderer(ABC):
    TITLE = "Blind Charging - Redacted Narrative"

    DISCLAIMER = """
The following narrative has been automatically extracted from its \
        original police report.
The narrative has been redacted to remove race-specific information, \
        but has otherwise not been modified.
<br/><br/>
This document was generated by an experimental version of the Blind Charging tool. \
        Please report any issues to
<a href="mailto:blind-charging@lists.stanford.edu">\
        blind-charging@lists.stanford.edu</a>.
"""

    @abstractmethod
    def __call__(self, redaction: RedactedText) -> MemoryFile: ...

    @classmethod
    def escape_for_xml(cls, text: str) -> str:
        """Escape text for HTML-style markup languages (HTML, platypus, etc).

        Args:
            text: The text to escape.

        Returns:
            The escaped text.
        """
        replacements = [
            ("&", "&amp;"),
            ("<", "&lt;"),
            (">", "&gt;"),
        ]
        for old, new in replacements:
            text = text.replace(old, new)
        return text
