import pytest

from ..common.context import Context
from ..common.text import RedactedText
from .text import TextRenderConfig


def decorate(txt: str) -> bytes:
    """Add the disclaimer header / footer to the given text."""
    header = (
        b"Blind Charging - Redacted Narrative\n\n\nThe following narrative has been a"
        b"utomatically extracted from its original police report.\nThe narrative ha"
        b"s been redacted to remove race-specific information, but has otherwise not b"
        b"een modified.\n\nThis document was generated by an experimental version of"
        b" the Blind Charging tool. Please report any issues to\n        blind-char"
        b"ging@lists.stanford.edu.\n\n\n=== NARRATIVE ===\n"
    )
    footer = b"\n\n=== END OF DOCUMENT ===\n"
    return header + txt.encode("utf-8") + footer


@pytest.mark.parametrize(
    "original, redacted, expected, debug",
    [
        (
            "Hello, world!",
            "Hello, [Person 1]!",
            "Hello, [Person 1]!",
            False,
        ),
        (
            "I took photos of Leopold ears.",
            "I took photos of [Subject 1]'s ears.",
            "I took photos of [Leopold -> Subject 1]'s ears.",
            True,
        ),
    ],
)
def test_render_text(original, redacted, expected, debug):
    cfg = TextRenderConfig.model_validate(
        {
            "engine": "render:text",
        }
    )
    rt = RedactedText(redacted, original, "[]")
    ctx = Context()
    if debug:
        ctx.debug = True

    result = cfg.driver(rt, ctx)
    assert result.content() == decorate(expected)
